id: com.github.moussetc.mattermost.plugin.emoticon2emoji
name: Emoticon to Emoji
description: "Add Slack emoticon to emoji conversion and some others (like XD to :laughing:) and allow customized mappings"
version: '1.0.0'
backend:
    executable: plugin
settings_schema:
    header: "The plugin applies both the [Slack emoticon->emoji mappings](https://get.slack.help/hc/en-us/articles/202931348-Use-emoji-and-emoticons#use-emoticons) and a customizable mappings list which can be edited below."
    settings:
        - key: CustomMatches
          type: text
          display_name: Custom mappings
          help_text: "Define your own emoticon to emoji mappings to replace the default mappings. The expected format is a JSON map. Don't put the colons for the emoji code and don't forget to escape any special characters ! To remove all custom mappings, put it to `{}`"
          default: "{ \":-3\": \"smiley\",	\":3\":  \"smiley\",	\"8-)\": \"sunglasses\",	\"8‑D\": \"smile\",	\"8D\":  \"smile\",	\"xD\":  \"laughing\",	\"xd\":  \"laughing\",	\"XD\":  \"laughing\",	\"=D\":  \"smile\",	\"=3\":  \"smile\",	\":c\":  \"frowning_face\",	\":<\":  \"frowning\",	\":@\":  \"rage\",	\":')\": \"joy\",	\"XP\":  \"stuck_out_tongue_closed_eyes\",	\"xp\":  \"stuck_out_tongue_closed_eyes\",	\":X\":  \"zipper_mouth_face\",	\"O:)\": \"angel\",	\">:)\": \"smiling_imp\"}"
    footer: |
        To report an issue, make a suggestion or a contribution, or fork your own version of the plugin, [check the repository](https://github.com/moussetc/mattermost-plugin-emoticon2emoji/).
