// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.github.moussetc.mattermost.plugin.emoticon2emoji",
  "name": "Emoticon to Emoji",
  "description": "Add Slack emoticon to emoji conversion and some others (like XD to :laughing:) and allow customized mappings",
  "homepage_url": "https://github.com/moussetc/mattermost-plugin-emoticon2emoji/",
  "support_url": "https://github.com/moussetc/mattermost-plugin-emoticon2emoji/issues",
  "release_notes_url": "https://github.com/moussetc/mattermost-plugin-emoticon2emoji/releases/tag/v0.1.0",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "2.1.0",
  "min_server_version": "5.20.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": "server/dist/plugin-freebsd-amd64.exe"
  },
  "settings_schema": {
    "header": "The plugin applies both the [Slack emoticon-\u003eemoji mappings](https://get.slack.help/hc/en-us/articles/202931348-Use-emoji-and-emoticons#use-emoticons) and a customizable mappings list which can be edited below.",
    "footer": "To report an issue, make a suggestion or a contribution, or fork your own version of the plugin, [check the repository](https://github.com/moussetc/mattermost-plugin-emoticon2emoji).",
    "settings": [
      {
        "key": "CustomMatches",
        "display_name": "Custom mappings",
        "type": "text",
        "help_text": "Define your own emoticon to emoji mappings to replace the default mappings. The expected format is a JSON map. Don't put the colons for the emoji code and don't forget to escape any special characters ! To remove all custom mappings, set it to {}",
        "placeholder": "",
        "default": "{ \":-3\": \"smiley\", \":3\": \"smiley\", \"8-)\": \"sunglasses\", \"8‑D\": \"smile\", \"8D\": \"smile\", \"xD\": \"laughing\", \"xd\": \"laughing\", \"XD\": \"laughing\", \"=D\": \"smile\", \"=3\": \"smile\", \":c\": \"frowning_face\", \":\u003c\": \"frowning\", \":@\": \"rage\", \":')\": \"joy\", \"XP\": \"stuck_out_tongue_closed_eyes\", \"xp\": \"stuck_out_tongue_closed_eyes\", \":X\": \"zipper_mouth_face\", \"O:)\": \"angel\", \"\u003e:)\": \"smiling_imp\"}"
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
